baseURL = "https://example.com/"
languageCode = "en-us"
title = "Ishill Demosite"
theme = "ishill"

pagination.pagerSize=5 # articles per page

enableGitInfo = true

mainSections = ['leaflets', 'monographs', 'imprints']

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Leaflets"
url = "/leaflets"
weight = 3

[[menu.main]]
name = "Monographs"
url = "/monographs"
weight = 4

[[menu.main]]
name = "Imprints"
url = "/imprints"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[params]
	mode = "auto" # color-mode → light,dark,toggle or auto
  customcss = []
  subtitle = "A demonstration of the Ishill zine publishing stack. Click About to learn more."
  submissions = "donotemail@example.com"

  # used in homepage "unfurl" for Slack and similar
  description = "Ishill makes it easy to create good-looking zine content on the web and in print."

  # Used in footer
  explainer = "makes it easy to create good-looking zine content on the web and in print."

  # Used for spacer pages to make zine pagelength divisible by 4
  spacer1 = '"You shovel sixteen tons and what do you get? Another day older and deeper in debt." — Merle Travis'
  spacer2 = '"Those are the heavy seven. Those are the ones that will infect your soul, curve your spine and keep the country from winning the war." — George Carlin'
  spacer3 = '"I do not consider myself an artist. I consider myself a very opinionated man who uses words as fighting tools." — Larry Kramer'

# Media type definitions

[mediaTypes]
  [mediaTypes."application/javascript"]
    delimiter = '.'
    suffixes = ['js']
  [mediaTypes."application/x-shellscript"]
    delimiter = '.'
    suffixes = ['sh']
  [mediaTypes."application/atom+xml"]
    delimiter = '.'
    suffixes = ["xml"]

[outputFormats.zineify]
  name = 'Zineify'
  basename = 'zineify'
  mediaType = "application/x-shellscript"
  isPlainText = true
  notAlternative = true

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom+xml"


[outputs]
  home = ["HTML", "zineify", "Atom"]
